# Generated by Django 4.2.2 on 2023-08-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ratig',
            new_name='rating',
        ),
    ]
